services:
  postgres:
    image: postgres:16-alpine
    container_name: timesheet-db
    environment:
      POSTGRES_DB: timesheet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - timesheet-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/TimesheetApp.API
      dockerfile: Dockerfile
    container_name: timesheet-backend
    ports:
      - "5282:5282"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=timesheet;Username=postgres;Password=postgres
    networks:
      - timesheet-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: timesheet-frontend
    ports:
      - "8080:80"
    environment:
      - BACKEND_URL=backend:5282
    depends_on:
      - backend
    networks:
      - timesheet-network

networks:
  timesheet-network:
    driver: bridge

volumes:
  postgres_data:
