services:
  backend:
    build:
      context: ./backend/TimesheetApp.API
      dockerfile: Dockerfile
    container_name: timesheet-backend
    ports:
      - "5282:5282"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    networks:
      - timesheet-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: timesheet-frontend
    ports:
      - "8080:80"
    environment:
      - BACKEND_URL=backend:5282
    depends_on:
      - backend
    networks:
      - timesheet-network

networks:
  timesheet-network:
    driver: bridge

volumes:
  postgres_data:
